# -*- coding: utf-8 -*-
"""Ejercicio Clase 13-POO - Pedro F Perez.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Rarky7jv4mdxiuIF876yDo6C_iCwrmz
"""

#Clase 13- POO
#nombre: Pedro F. Perez 
#Crear una clase llamada Cuenta que tendrá los siguientes atributos: titular (que es una persona) y cantidad 
# (puede tener decimales). El titular será obligatorio y la cantidad es opcional. 
# Construye los siguientes métodos para la clase: 
# Un constructor.
# mostrar(): Muestra los datos de la cuenta. 
# ingresar(cantidad): se ingresa una cantidad a la cuenta, si la cantidad introducida es negativa, no se hará nada. 
# retirar(cantidad): se retira una cantidad a la cuenta. La cuenta puede estar en números rojos

class Cuenta:
  especie = "banco"                                                        #atributos de clase

  def __init__(self,apellido,nombre,cuenta,montoInicial):                               #constructor.  
    self.apellido=apellido                                                 #Atributos de instancia
    self.nombre=nombre
    self.__cuenta=cuenta                                                   #Atributos de instancia           
    self.__monto=montoInicial  

  def __str__(self):
    return f"apellido: {self.apellido}{self.nombre}, Monto en su cuenta es:{self.monto}"  

  def ingreso(self):                                                       #Método sin argumentos
    ingreso=float(input("valor a ingresar es: "))
    if ingreso <0 : return print ("valor de deposito es invalido: no se modificara el monto")
#    else: pass
    self.__monto=self.__monto + ingreso
    print (f"El monto actual con el nuevo ingreso es: {self.__monto}")     # colocar f permite imprimir el dato en {}
    return
  def egreso(self): 
    retiro=float(input("valor a retirar es: "))
    self.__monto=self.__monto - retiro
    print (f"el monto actual con el retiro es: {self.__monto}")            # colocar f permite imprimir el dato en {}
    return 

print ("Ingrese los siguientes datos")
apellido=str(input("Ingrese su Apellido: "))
nombre=str(input("Ingrese su Nombre: "))
numero_cuenta=int(input("Ingrese su numero de cuenta: "))
montoInicial=345
cuenta1=Cuenta(apellido,nombre,numero_cuenta,montoInicial)

cuenta1.ingreso()
cuenta1.egreso()